spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taskmanager}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:taskmanager}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:taskmanager}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=false

spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_history
spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true

security.jwt.secret=fC8!opg?Naq!dH0U=,Btcu[2N,VaC@NKuuwd0M-N#O>
security.jwt.expiration-ms=86400000

seed.default-user-password=12345678

spring.cache.type=simple